### ISSUE TITLE
Not loading properly videos

### ISSUE THREAD

**Issue by Freakill** [naulacambra/Multimodal-Analysis-Tool#2]
When loading a video, the dialog lets choose a file (in this case an .mp4 file), says it is loaded properly, but then no video is loaded, thus nothing can be played.

**Comment by naulacambra** [comment]
Sorry, but I can't replay your error. Are you trying to load the albert_1_blau_alex_porta.mp4 file or another one?

**Comment by Freakill** [comment]
yes, this happens to me when I try to load your video. The error that the QT Creator Console outputs whenever I click to any of the Play/Pause/Stop options once the video is loaded is the following:
"DirectShowPlayerService::doRender: Unresolved error code 80040266".

**Comment by naulacambra** [comment]
Since you've installed the codecs and it works, i'll close this issue
